services:
  db:
    image: postgres:14
    networks:
      - camagru-network
    ports:
      - "5432:5432"
    env_file:
      - ./back/.env
    volumes:
      - pgdata:/usr/src/pgdata/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
    env_file:
      - ./back/.env
    networks:
      - camagru-network

  front:
    build:
      context: ./front
    ports:
      - "8080:80"
    networks:
      - camagru-network

volumes:
  pgdata:

networks:
  camagru-network:
    driver: bridge
