services:
  db:
    image: postgres:14
    networks:
      - camagru-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/usr/src/pgdata/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - camagru-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - camagru-network
    environment:
      -API_AUTHORIZATION_TOKEN: ${API_AUTHORIZATION_TOKEN}

volumes:
  pgdata:

networks:
  camagru-network:
    driver: bridge
