services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./back/.env
    networks:
      - camagru

  front:
    build:
      context: ./front
    ports:
      - "8080:80"
    networks:
      - camagru
  db:
    image: postgres:14
    networks:
      - camagru
    # ports:
    #   - "5432:5432"
    # env_file:
    #   - ./back/.env
    # volumes:
    #   - pgdata:/usr/src/pgdata/data

volumes:
  pgdata:

networks:
  camagru:
