### get user by id
GET http://localhost:5000/api/v1/users

### register a user
POST http://localhost:5000/api/v1/auth/register
content-type: application/json

{
 "username": "test2",
 "email": "alt.bm-06xlvwr@yopmail.com",
 "adress": "test",
 "passwd": "Alt.bm-06xlvwr@yopmail.com",
 "firstName": "Benois",
 "lastName": "DUPOND"
}

### verify user
POST http://localhost:5000/api/v1/auth/verify/-m38hzdhh-n6oowi
content-type: application/json

{}


### get all users
GET http://localhost:5000/api/v1/users/session-m3zyg1kv-nz8d2z
Content-Type: application/json