### get user by id
GET http://localhost:5000/api/v1/users

### create a user
POST http://localhost:5000/api/v1/users
content-type: application/json

{
 "username": "toto2",
 "email": "test2@gmail.com",
 "adress": "test",
 "passwd": "admin123"
}

### get all users
GET http://localhost:5000/api/v1/users