### get user by id
GET http://localhost:5000/api/v1/users/id

### register a user
POST http://localhost:5000/api/v1/auth/register
content-type: application/json

{
 "username": "test1",
 "email": "test1@yopmail.com",
 "adress": "test",
 "passwd": "admin123"
}

### verify user
POST http://localhost:5000/api/v1/auth/verify/-m3786uom-0q811m
content-type: application/json

{}


### get all users
GET http://localhost:5000/api/v1/users