name: Node.js CI

on:
  push:
    branches:
     - "**"  # Match all branches
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install, Build, and Test
      run: |
        cd back
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
        npm run build --if-present
        npm test
